export const PUBLISHERS_FETCHED = 'publisher.PUBLISHERS_FETCHED';
export const PUBLISHERS_FETCH_FAILED = 'publisher.PUBLISHERS_FETCH_FAILED';
export const PUBLISHER_UPDATED = 'publisher.PUBLISHER_UPDATED';
export const PUBLISHER_UPDATE_FAILED = 'publisher.PUBLISHER_UPDATE_FAILED';
export const CLEAR_ERROR = 'publisher.CLEAR_ERROR';
export const PUBLISHER_LOGS_UPDATED = 'publisher.PUBLISHER_LOGS_UPDATED';
export const PUBLISHER_LOGS_UPDATED_FAILED =
  'publisher.PUBLISHER_LOGS_UPDATED_FAILED';
