on:
  release:
    types: [published]
    
name: Deploy to Heroku
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Check tag
      uses: actions/bin/filter@master
      with:
        args: tag v*

    - name: Build with NPM
      uses: actions/npm@master
      with:
        args: install
    
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        HEROKU_APP: ${{secrets.HEROKU_APP}}
      run:
        git push https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/${{secrets.HEROKU_APP}}.git HEAD:master
